name: Sync Repository

# 触发条件：每24小时自动执行和手动触发
on:
  schedule:
    # 每天UTC时间00:00执行（北京时间08:00）
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 支持手动触发

permissions:
  contents: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Add remote source repository
      run: |
        git remote add source https://cnb.cool/EnderRealm/public/MCBEPackCrypt
        git remote -v
    
    - name: Fetch from source repository
      run: |
        git fetch source
    
    - name: Backup protected files
      run: |
        # 备份需要保护的文件
        mkdir -p /tmp/backup
        cp -r .github /tmp/backup/
        cp SYNC_INFO.md /tmp/backup/ 2>/dev/null || true
        cp SYNC_INFO_ZH.md /tmp/backup/ 2>/dev/null || true
        echo "Protected files backed up"
    
    - name: Merge from source repository
      run: |
        # 直接合并源仓库的更改
        git merge source/main --no-edit || {
          echo "Merge conflict detected, using source version for conflicted files except protected ones"
          git checkout source/main -- . || true
          git checkout HEAD -- .github/ SYNC_INFO.md SYNC_INFO_ZH.md 2>/dev/null || true
          git add .
        }
        echo "Merge completed"
    
    - name: Restore protected files and update timestamps
      run: |
        # 恢复保护的文件并更新时间戳
        cp -r /tmp/backup/.github .
        CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S UTC')
        if [ -f "/tmp/backup/SYNC_INFO.md" ]; then
          sed "s/\[AUTO_UPDATE_TIME\]/$CURRENT_TIME/g" /tmp/backup/SYNC_INFO.md > SYNC_INFO.md
        fi
        if [ -f "/tmp/backup/SYNC_INFO_ZH.md" ]; then
          sed "s/\[AUTO_UPDATE_TIME\]/$CURRENT_TIME/g" /tmp/backup/SYNC_INFO_ZH.md > SYNC_INFO_ZH.md
        fi
        echo "Protected files restored with updated timestamp"
    
    - name: Commit and push changes
      run: |
        # 添加所有更改并提交
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Auto-sync from source repository [$(date '+%Y-%m-%d %H:%M:%S UTC')]"
          git push origin main
          echo "✅ Changes committed and pushed successfully"
        else
          echo "ℹ️ No changes to commit"
        fi
    
    - name: Sync summary
      run: |
        echo "🔄 Repository sync completed at $(date)"
        echo "📍 Source: https://cnb.cool/EnderRealm/public/MCBEPackCrypt"
        echo "🎯 Target: ${{ github.repository }}"
        echo "✨ Sync process finished successfully"